name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      # Build APK Release
      - name: Build apk release module
        run: ./gradlew assemble

      # Create APK Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: UPLOAD APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          path: app/build/outputs/apk/release/
          name: AttendEase.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}