name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Permission
        run: chmod +x gradlew

      - name: Build Gradle
        run: ./gradlew build

      # Build APK Release
      - name: Build Debug APK
        run: bash ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk


      # Create APK Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}